image: barichello/godot-ci:3.3

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/

stages:
  - build
  - deploy

variables:
  EXPORT_NAME: godot-starter

before_script:
  # Remove lfs hook (https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2245)
  - rm .git/hooks/post-checkout || true

web:
  when: manual
  only:
    - master
  stage: build
  script:
    - mkdir -v -p build/web
    - godot -v --export "HTML5" build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web

itchio:web:
  stage: deploy 
  script:
    - butler push ./build/web $ITCHIO_USERNAME/$ITCHIO_GAME:web
  dependencies:
    - web
